### ISSUE TITLE
USER STORY: View a specific category of products

### ISSUE THREAD

**Issue by barkode** [barkode/FreshlyRooted-grocery-market-ci#19]
As a **Shopper**, I want to be able to **view a specific category of products** so that I can **quickly find products I’m interested in**.

### **Acceptance Criteria:**

- [x] Category options display on the product listing page.
- [x]  Selecting a category shows only the relevant products.

### **Tasks:**

- [x] Add category filters on the product listing page.
- [x] Link categories in the navigation menu.
