### ISSUE TITLE
USER STORY: View individual product details

### ISSUE THREAD

**Issue by barkode** [barkode/FreshlyRooted-grocery-market-ci#20]
As a **Shopper**, I want to be able to **view individual product details** so that I can **identify the price, description, rating, image, and available sizes**.

### **Acceptance Criteria:**

- [x] Product details are visible when a product is selected.
- [x]  Users can see different available sizes and add the product to their cart.

### **Tasks:**

- [x] Build a detailed product page with all relevant details.
- [x] Implement display for price, description, rating, images, and size options.
