### ISSUE TITLE
USER STORY: Quickly identify deals

### ISSUE THREAD

**Issue by barkode** [barkode/FreshlyRooted-grocery-market-ci#21]
As a **Shopper**, I want to be able to **quickly identify deals, clearance items, and special offers** so that I can **take advantage of savings**.

### **Acceptance Criteria:**

- [x] Promotional products are visibly marked with “Deal” or “Clearance” tags.
- [x]  Special offers are accessible from the homepage.

### **Tasks:**

- [x] Highlight deals and clearance items on the product listing page.
- [x] Create a separate section for special offers.
