### ISSUE TITLE
USER STORY: View the total of purchases

### ISSUE THREAD

**Issue by barkode** [barkode/FreshlyRooted-grocery-market-ci#22]
As a **Shopper**, I want to be able to **easily view the total of my purchases at any time** so that I can **avoid overspending**.

### **Acceptance Criteria:**

- [x] The cart icon displays the correct total amount in real-time.
- [x]  Users can view itemized cart details on hover or click.

### **Tasks:**

- [x] Display a persistent shopping cart icon showing the total amount.
- [x] Update the cart total dynamically as products are added or removed.
