### ISSUE TITLE
USER STORY: Email confirmation after registering

### ISSUE THREAD

**Issue by barkode** [barkode/FreshlyRooted-grocery-market-ci#27]
As a **Site User**, I want to be able to **receive an email confirmation after registering** so that I can **verify my account registration**.

### **Acceptance Criteria:**

- [x] Users receive an email immediately after registering.
- [x]  The email contains a confirmation link or message.

### **Tasks:**

- [x] Configure email notifications for account registration.
- [x] Set up a confirmation message with account details.
