### ISSUE TITLE
USER STORY: Personalize profile

### ISSUE THREAD

**Issue by barkode** [barkode/FreshlyRooted-grocery-market-ci#28]
As a **Site User**, I want  to be able to a **personalized profile** where I can **view my order history, confirmations, and save payment information**.

### **Acceptance Criteria:**

- [ ] Order history and payment methods display correctly in the profile.
- [x]  Users can update saved information as needed.

### **Tasks:**

- [x] Design a user profile page with order history and saved payment methods.
- [x] Link profile to individual orders for details.
