### ISSUE TITLE
USER STORY: Sort products

### ISSUE THREAD

**Issue by barkode** [barkode/FreshlyRooted-grocery-market-ci#30]
As a **Shopper**, I want to be able to **sort products to easily** so that I can **identify the best-rated, best-priced, and category-specific items**.

### **Acceptance Criteria:**

- [x] Sort options are visible and functional.
- [x] Products are sorted accordingly when a sort option is selected.

### **Tasks:**

- [x] Add sorting options on the product listing page.
- [x] Implement sorting based on rating, price, and alphabetical order.
