### ISSUE TITLE
USER STORY: Sort a specific category of products

### ISSUE THREAD

**Issue by barkode** [barkode/FreshlyRooted-grocery-market-ci#31]
As a **Shopper**, I want to be able to **sort a specific category of products** so that I can to **quickly find the best-rated or best-priced items**.

### **Acceptance Criteria:**

- [x] Sort options work within each category.
- [x]  Sorting options reflect in the displayed products within the selected category.

### **Tasks:**

- [x] Implement sorting for individual categories.
- [x] Ensure category sorting integrates with other filters (e.g., price range).
