### ISSUE TITLE
USER STORY: Search for products by name or description

### ISSUE THREAD

**Issue by barkode** [barkode/FreshlyRooted-grocery-market-ci#33]
As a **Shopper**, I want to be able to **search for products by name or description** so that I can **find a specific item easily**.

### **Acceptance Criteria:**

- [x] Users can search by product name or keywords.
- [x]  Relevant products display instantly based on the search query.

### **Tasks:**

- [x] Add a search bar on the product listing page.
- [x] Implement search functionality for product names and descriptions.
