### ISSUE TITLE
USER STORY: Show search term and the number of results

### ISSUE THREAD

**Issue by barkode** [barkode/FreshlyRooted-grocery-market-ci#34]
As a **Shopper**, I want to be able to **see my search term and the number of results**  so thant I can **know if the product I want is available**.

### **Acceptance Criteria:**

- [x] The search term and result count are visible at the top of the search results.
- [x]  Accurate results and counts display in real-time.

### **Tasks:**

- [x] Display search term and result count in the search area.
- [x] Update count dynamically with each search or filter adjustment.
