### ISSUE TITLE
USER STORY: Edit/update products

### ISSUE THREAD

**Issue by barkode** [barkode/FreshlyRooted-grocery-market-ci#39]
As a **Store Owner**, I want to be able to **edit/update products** so that I can **change prices, descriptions, or images**.

### **Acceptance Criteria:**

- [x] Updated products reflect immediately on the site.
- [x]  Admin can preview changes before saving.

### **Tasks:**

- [x] Add an edit form for each product in the admin panel.
- [x] Allow updates to any product details, with live preview.
