### ISSUE TITLE
USER STORY: Delete products

### ISSUE THREAD

**Issue by barkode** [barkode/FreshlyRooted-grocery-market-ci#40]
As a **Store Owner**, I want to be able to **delete products** so that i can **remove items no longer for sale**.

### **Acceptance Criteria:**

- [x] Deleted products are removed from the live site.
- [x]  Admin is prompted to confirm deletion.

### **Tasks:**

- [x] Implement delete functionality with confirmation prompts.
- [x] Archive deleted products for future reference.
