### ISSUE TITLE
USER STORY: Manage user reviews

### ISSUE THREAD

**Issue by barkode** [barkode/FreshlyRooted-grocery-market-ci#42]
As a **Store Owner**, I want to be able to **manage user reviews and moderate inappropriate content** so that I can **maintain a professional and user-friendly store**.

### **Acceptance Criteria:**

- [x] Admins can delete or hide reviews.
- [x]  Flagged reviews do not display publicly until approved.

### **Tasks:**

- [x] Implement a review moderation system with options to delete or flag inappropriate content.
- [x] Set up notifications for new reviews.
