### ISSUE TITLE
USER STORY: Customer support

### ISSUE THREAD

**Issue by barkode** [barkode/FreshlyRooted-grocery-market-ci#43]
As a **Shopper**, I want to be able to **access customer support or live chat** so that I can **quickly resolve any issues with my purchase or account**.

### **Acceptance Criteria:**

- [x] Users can access support directly from their account or the main site.
- [x]  A support confirmation email is sent if a message is submitted.

### **Tasks:**

- [x] Add a "Contact Us" or "Live Chat" button on the website.
- [x] Ensure 24/7 support availability or queue system.
