### ISSUE TITLE
USER STORY: Shopper email issue notifications

### ISSUE THREAD

**Issue by barkode** [barkode/FreshlyRooted-grocery-market-ci#46]
As a **Shopper**, I want to be able to **receive an email notification if there is an issue with my order** so that I can **be informed immediately**.

### **Acceptance Criteria:**

- [x] Users receive an immediate email if there are any order issues.
- [x]  Email includes clear details on the issue and a link for further support.

### **Tasks:**

- [x] Develop automated email notifications for issues like payment failures, out-of-stock items, or delays.
- [x] Link email notifications to order status updates.
