### ISSUE TITLE
USER STORY: Notified of limited-time discounts

### ISSUE THREAD

**Issue by barkode** [barkode/FreshlyRooted-grocery-market-ci#49]
As a **Shopper**, I want to be able to **notified of limited-time discounts** so that I **don’t miss out on sales**.

### **Acceptance Criteria:**

- [x] Limited-time offers are shown via a pop-up or banner during the promotional period.
- [x]  Users can click to view discounted items directly.

### **Tasks:**

- [x] Implement pop-up notifications on the site for limited-time offers.
- [x] Allow users to opt into sale notifications.
