### ISSUE TITLE
USER STORY: Show discounted price to each item

### ISSUE THREAD

**Issue by barkode** [barkode/FreshlyRooted-grocery-market-ci#51]
As a **Shopper**, I want to be able to **see the discounted price clearly on each product listing** so that I can **know the exact savings**.

### **Acceptance Criteria:**

- [x] Discounted items clearly show both original and discounted prices.
- [x] Savings are displayed as a percentage or dollar amount.

### **Tasks:**

- [x] Display the original and discounted prices on products with active discounts.
- [x] Show percentage or dollar amount saved next to the price.
