### ISSUE TITLE
USER STORY: Add to favorites

### ISSUE THREAD

**Issue by barkode** [barkode/FreshlyRooted-grocery-market-ci#53]
As a **Shopper**, I want to be able to **mark items as "Favorites" on the product listing page** so that I can **easily save them for later**.

### **Acceptance Criteria:**

- [x] The “Favorite” icon is visible on each product in the listing.
- [x] Clicking the icon saves the item to the user's favorites and displays a notification confirming the action.
- [x] The icon changes visually to indicate when an item is favorited.

### **Tasks:**

- [x] Add a “Favorite” or “Wishlist” icon on each product in the product listing view.
- [x] Implement functionality to save the selected item to the user’s favorites when the icon is clicked.
