### ISSUE TITLE
USER STORY: Select the size and quantity when purchasing

### ISSUE THREAD

**Issue by barkode** [barkode/FreshlyRooted-grocery-market-ci#70]
As a **Shopper**, I want to **select the size and quantity when purchasing** so that I can **ensure accuracy**.

### **Acceptance Criteria:**

- [x] Size and quantity options are available on the product page.
- [x]  Users can’t add out-of-stock sizes or quantities to the cart.

### **Tasks:**

- [x] Add size and quantity selection on the product page.
- [x] Validate size and quantity before adding to the cart.
