### ISSUE TITLE
USER STORY: Adjust the quantity of items before checkout

### ISSUE THREAD

**Issue by barkode** [barkode/FreshlyRooted-grocery-market-ci#72]
As a **Shopper**, I want to be able to **adjust the quantity of items in my bag easily before checkout** so that I can **add or delete from my bag**.

### **Acceptance Criteria:**

- [x] Users can adjust quantities directly in the shopping bag.
- [x]  Updated totals display immediately.

### **Tasks:**

- [x] Add quantity adjustment options in the shopping bag.
- [x] Update totals and availability as quantities change.
