### ISSUE TITLE
USER STORY: Enter payment information

### ISSUE THREAD

**Issue by barkode** [barkode/FreshlyRooted-grocery-market-ci#73]
As a **Shopper**, I want to be able to **enter payment information quickly** so that I can **check out without hassle**.

### **Acceptance Criteria:**

- [x] The payment form is user-friendly and error-free.
- [x] Payment can be completed with a valid method.

### **Tasks:**

- [x] Build a payment information form at checkout.
- [x] Enable secure payment methods integration (e.g., credit card, PayPal).
