### ISSUE TITLE
USER STORY: Feel personal and payment information

### ISSUE THREAD

**Issue by barkode** [barkode/FreshlyRooted-grocery-market-ci#74]
As a **Shopper**, I want to be able to **feel my personal and payment information is safe and secure** so that I can **add my personal information securely**.

### **Acceptance Criteria:**

- [x] Payment is processed securely through HTTPS.
- [x]  Security notifications reassure users of data protection.

### **Tasks:**

- [x] Implement SSL/TLS encryption and secure payment gateway.
- [x] Add clear privacy policy and security icons.
