### ISSUE TITLE
USER STORY: Order confirmation after checkout

### ISSUE THREAD

**Issue by barkode** [barkode/FreshlyRooted-grocery-market-ci#75]
As a **Shopper**, I want to be able to **view order confirmation after checkout** so that I can **verify my order before purchase**.

### **Acceptance Criteria:**

- [x] Users receive a confirmation page with complete order details.
- [x]  A unique order ID is generated for tracking.

### **Tasks:**

- [x] Create an order confirmation page with order details.
- [x] Generate a unique order ID and display a summary.
